# Generated by Django 5.0.7 on 2024-08-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_posts_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(related_name='tag_posts', to='news.tags'),
        ),
    ]
