# Generated by Django 5.0.7 on 2024-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_information_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube (url)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='facebook',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Facebook (url)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='instagram',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Instagram (url)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='twitter',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Twitter (url)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='whatsapp',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Whatsapp (url)'),
        ),
    ]
