# Generated by Django 5.0.7 on 2024-08-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_information_youtube_alter_information_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, default='#', null=True, verbose_name='Twitter (url)')),
                ('facebook', models.URLField(blank=True, default='#', null=True, verbose_name='Facebook (url)')),
                ('instagram', models.URLField(blank=True, default='#', null=True, verbose_name='Instagram (url)')),
                ('youtube', models.URLField(blank=True, default='#', null=True, verbose_name='Youtube (url)')),
                ('whatsapp', models.URLField(blank=True, default='#', null=True, verbose_name='Whatsapp (url)')),
            ],
            options={
                'verbose_name': 'Socials',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.RemoveField(
            model_name='information',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='information',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='information',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='information',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='information',
            name='youtube',
        ),
    ]
