# Generated by Django 5.0.7 on 2024-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_socials_remove_information_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socials',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='youtube',
        ),
        migrations.AddField(
            model_name='information',
            name='socials',
            field=models.ManyToManyField(to='home.socials'),
        ),
        migrations.AddField(
            model_name='socials',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='socials',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socials',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
