# Generated by Django 5.0.7 on 2024-08-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_socials_facebook_remove_socials_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
