# Generated by Django 5.0.7 on 2024-08-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_volunteers_information_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='information',
            name='socials',
            field=models.ManyToManyField(blank=True, to='home.socials'),
        ),
    ]
