# Generated by Django 5.0.7 on 2024-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_information_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteers',
            options={'verbose_name': 'Volunteer', 'verbose_name_plural': 'Volunteers'},
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
